version: "3.8"
services:
  gpu-dev:
    image: my-gpu-dev-env
    container_name: my-dev-container
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: bash