version: "3.8"
services:
  app:
    image: my-gpu-dev-env
    container_name: my-dev-container
    command: bash -c "git clone https://github.com/YitKubo/docker_test.git /workspace/docker_test 2>/dev/null || true && bash"
    tty: true
    stdin_open: true
    volumes:
      - .:/workspace
    working_dir: /workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]