version: "3"
services:
  app:
    image: my-gpu-dev-env
    container_name: my-dev-container
    command: bash
    tty: true
    stdin_open: true
    volumes:
      - .:/workspace
    working_dir: /workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]