FROM nvidia/cuda:12.2.2-cudnn8-devel-ubuntu22.04

RUN apt-get update && apt-get install -y \
    python3.10 python3.10-dev python3-pip curl git \
    && rm -rf /var/lib/apt/lists/*

RUN python3.10 -m pip install --upgrade pip

# ✅ cu121に変更
RUN python3.10 -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

RUN python3.10 -m pip install numpy pandas matplotlib jupyter

WORKDIR /workspace

# /workspace 配下にクローン
RUN git clone https://github.com/YitKubo/docker_test.git /workspace/docker_test

CMD ["bash"]
